# Generated by Django 4.2.7 on 2023-11-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('is_favorite', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
